# portfolio_data.py
# All basket compositions, stock history, and buy-price details ported
# verbatim from data.js.  Variable names match the architecture spec.

PORTFOLIOS_DATA = {

    # ─────────────────────────────────────────────────────────────────────────
    # GREEN ENERGY — 25 stocks, Σ allocation = 100%
    # ─────────────────────────────────────────────────────────────────────────
    "Green_Energy": [
        {"nseCode": "EBGNG",      "allocation": 0.05,  "buyPrice": 333.30},
        {"nseCode": "SANSERA",    "allocation": 0.03,  "buyPrice": 1959.30},
        {"nseCode": "TDPOWERSYS", "allocation": 0.05,  "buyPrice": 128.22},
        {"nseCode": "ENRIN",      "allocation": 0.03,  "buyPrice": 2546.43},
        {"nseCode": "AVALON",     "allocation": 0.03,  "buyPrice": 1000.06},
        {"nseCode": "ATHERENERG", "allocation": 0.03,  "buyPrice": 678.69},
        {"nseCode": "NEOGEN",     "allocation": 0.02,  "buyPrice": 1370.93},
        {"nseCode": "TRANSRAILL", "allocation": 0.025, "buyPrice": 598.61},
        {"nseCode": "GANECOS",    "allocation": 0.02,  "buyPrice": 737.12},
        {"nseCode": "TATAPOWER",  "allocation": 0.04,  "buyPrice": 401.81},
        {"nseCode": "SBCL",       "allocation": 0.04,  "buyPrice": 253.69},
        {"nseCode": "JASH",       "allocation": 0.04,  "buyPrice": 581.46},
        {"nseCode": "FIEMIND",    "allocation": 0.035, "buyPrice": 786.53},
        {"nseCode": "SYRMA",      "allocation": 0.06,  "buyPrice": 562.91},
        {"nseCode": "LIQUIDCASE", "allocation": 0.03,  "buyPrice": 112.16},
        {"nseCode": "WAAREEENER", "allocation": 0.05,  "buyPrice": 2597.89},
        {"nseCode": "POWERMECH",  "allocation": 0.03,  "buyPrice": 3258.93},
        {"nseCode": "JAINREC",    "allocation": 0.035, "buyPrice": 404.55},
        {"nseCode": "QPOWER",     "allocation": 0.02,  "buyPrice": 427.45},
        {"nseCode": "SKIPPER",    "allocation": 0.05,  "buyPrice": 241.28},
        {"nseCode": "EMMVEE",     "allocation": 0.03,  "buyPrice": 229.64},
        {"nseCode": "TRITURBINE", "allocation": 0.03,  "buyPrice": 110.57},
        {"nseCode": "POCL",       "allocation": 0.035, "buyPrice": 1034.19},
        {"nseCode": "BORORENEW",  "allocation": 0.06,  "buyPrice": 582.05},
        {"nseCode": "HBLENGINE",  "allocation": 0.05,  "buyPrice": 655.12},
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # MID & SMALL CAP — 29 stocks, Σ allocation = 100%
    # ─────────────────────────────────────────────────────────────────────────
    "Mid_Small_Cap": [
        {"nseCode": "AARTIPHARM", "allocation": 0.04,  "buyPrice": 788.07},
        {"nseCode": "ACUTAAS",    "allocation": 0.04,  "buyPrice": None},
        {"nseCode": "ASTRAMICRO", "allocation": 0.04,  "buyPrice": 1088.61},
        {"nseCode": "BORORENEW",  "allocation": 0.04,  "buyPrice": 2369.00},
        {"nseCode": "CENTUM",     "allocation": 0.05,  "buyPrice": 910.51},
        {"nseCode": "GANECOS",    "allocation": 0.02,  "buyPrice": 791.10},
        {"nseCode": "GENESYS",    "allocation": 0.05,  "buyPrice": 388.00},
        {"nseCode": "GOKEX",      "allocation": 0.03,  "buyPrice": None},
        {"nseCode": "GOLDIAM",    "allocation": 0.035, "buyPrice": 172.64},
        {"nseCode": "GROWW",      "allocation": 0.04,  "buyPrice": None},
        {"nseCode": "HBLENGINE",  "allocation": 0.05,  "buyPrice": 478.30},
        {"nseCode": "HLEGLAS",    "allocation": 0.025, "buyPrice": 1312.48},
        {"nseCode": "IMFA",       "allocation": 0.025, "buyPrice": 1132.00},
        {"nseCode": "INTELLECT",  "allocation": 0.03,  "buyPrice": 1714.16},
        {"nseCode": "INTERARCH",  "allocation": 0.025, "buyPrice": 1056.28},
        {"nseCode": "KDDL",       "allocation": 0.02,  "buyPrice": 849.81},
        {"nseCode": "KRN",        "allocation": 0.03,  "buyPrice": None},
        {"nseCode": "LIQUIDCASE", "allocation": 0.055, "buyPrice": 135.34},
        {"nseCode": "MOLDTKPAC",  "allocation": 0.025, "buyPrice": 848.34},
        {"nseCode": "SAMBHV",     "allocation": 0.05,  "buyPrice": 101.57},
        {"nseCode": "SANSERA",    "allocation": 0.05,  "buyPrice": 2136.68},
        {"nseCode": "SBCL",       "allocation": 0.035, "buyPrice": 273.74},
        {"nseCode": "SJS",        "allocation": 0.025, "buyPrice": 1766.45},
        {"nseCode": "SUPRAJIT",   "allocation": 0.03,  "buyPrice": 475.58},
        {"nseCode": "SYRMA",      "allocation": 0.03,  "buyPrice": 548.75},
        {"nseCode": "TDPOWERSYS", "allocation": 0.025, "buyPrice": 325.78},
        {"nseCode": "URBANCO",    "allocation": 0.025, "buyPrice": 2401.09},
        {"nseCode": "WAAREEENER", "allocation": 0.03,  "buyPrice": 964.60},
        {"nseCode": "ZENTEC",     "allocation": 0.03,  "buyPrice": None},
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # IPO BASKET — 24 stocks, Σ allocation = 100%
    # ─────────────────────────────────────────────────────────────────────────
    "IPO_Basket": [
        {"nseCode": "AJAXENGG",   "allocation": 0.04,  "buyPrice": 603.39},
        {"nseCode": "ALLTIME",    "allocation": 0.03,  "buyPrice": 300.89},
        {"nseCode": "ARIS",       "allocation": 0.04,  "buyPrice": 178.31},
        {"nseCode": "ATHERENERG", "allocation": 0.05,  "buyPrice": 561.88},
        {"nseCode": "BLACKBUCK",  "allocation": 0.05,  "buyPrice": 474.35},
        {"nseCode": "CPPLUS",     "allocation": 0.035, "buyPrice": 1626.83},
        {"nseCode": "EBGNG",      "allocation": 0.07,  "buyPrice": 330.25},
        {"nseCode": "EMMVEE",     "allocation": 0.03,  "buyPrice": 231.55},
        {"nseCode": "EPACKPEB",   "allocation": 0.04,  "buyPrice": 291.79},
        {"nseCode": "GROWW",      "allocation": 0.04,  "buyPrice": 168.74},
        {"nseCode": "INTERARCH",  "allocation": 0.04,  "buyPrice": 1413.69},
        {"nseCode": "IXIGO",      "allocation": 0.03,  "buyPrice": 216.29},
        {"nseCode": "JAINREC",    "allocation": 0.05,  "buyPrice": 416.54},
        {"nseCode": "KRN",        "allocation": 0.04,  "buyPrice": 843.19},
        {"nseCode": "LAXMIDENTL", "allocation": 0.035, "buyPrice": 290.41},
        {"nseCode": "MEESHO",     "allocation": 0.03,  "buyPrice": 151.35},
        {"nseCode": "MOBIKWIK",   "allocation": 0.04,  "buyPrice": 229.25},
        {"nseCode": "QPOWER",     "allocation": 0.05,  "buyPrice": 886.90},
        {"nseCode": "SAILIFE",    "allocation": 0.04,  "buyPrice": 663.24},
        {"nseCode": "SAMBHV",     "allocation": 0.07,  "buyPrice": 101.02},
        {"nseCode": "SETL",       "allocation": 0.04,  "buyPrice": None},
        {"nseCode": "UNIMECH",    "allocation": 0.03,  "buyPrice": 936.10},
        {"nseCode": "URBANCO",    "allocation": 0.04,  "buyPrice": 122.64},
        {"nseCode": "WAAREEENER", "allocation": 0.04,  "buyPrice": 2127.98},
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # TRENDS TRIOLOGY — 19 stocks, Σ = 100%
    # ─────────────────────────────────────────────────────────────────────────
    "Trends_Triology": [
        {"nseCode": "AARTIPHARM",  "allocation": 0.05, "buyPrice": 705.84},
        {"nseCode": "ACUTAAS",     "allocation": 0.07, "buyPrice": None},
        {"nseCode": "AEROFLEX",    "allocation": 0.05, "buyPrice": None},
        {"nseCode": "AETHER",      "allocation": 0.05, "buyPrice": None},
        {"nseCode": "ATHERENERG",  "allocation": 0.07, "buyPrice": None},
        {"nseCode": "CENTUM",      "allocation": 0.05, "buyPrice": 2487.45},
        {"nseCode": "DYNAMATECH",  "allocation": 0.07, "buyPrice": 9511.25},
        {"nseCode": "E2E",         "allocation": 0.04, "buyPrice": 2568.18},
        {"nseCode": "EBGNG",       "allocation": 0.06, "buyPrice": 359.91},
        {"nseCode": "GENESYS",     "allocation": 0.08, "buyPrice": 761.63},
        {"nseCode": "GROWW",       "allocation": 0.05, "buyPrice": 176.12},
        {"nseCode": "ICEMAKE",     "allocation": 0.03, "buyPrice": 772.56},
        {"nseCode": "NEOGEN",      "allocation": 0.03, "buyPrice": 1308.68},
        {"nseCode": "RACLGEAR",    "allocation": 0.03, "buyPrice": 1365.75},
        {"nseCode": "SAILIFE",     "allocation": 0.03, "buyPrice": None},
        {"nseCode": "SAMBHV",      "allocation": 0.05, "buyPrice": 103.79},
        {"nseCode": "SANSERA",     "allocation": 0.07, "buyPrice": None},
        {"nseCode": "SHAILY",      "allocation": 0.07, "buyPrice": 1769.90},
        {"nseCode": "WAAREEENER",  "allocation": 0.05, "buyPrice": 3173.03},
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # TECHSTACK — 17 stocks, Σ allocation = 100%
    # ─────────────────────────────────────────────────────────────────────────
    "Techstack": [
        {"nseCode": "LENSKART",   "allocation": 0.04, "buyPrice": 427.94},
        {"nseCode": "ATHERENERG", "allocation": 0.04, "buyPrice": 616.50},
        {"nseCode": "E2E",        "allocation": 0.06, "buyPrice": 2052.40},
        {"nseCode": "BLACKBUCK",  "allocation": 0.03, "buyPrice": 542.85},
        {"nseCode": "PARAS",      "allocation": 0.04, "buyPrice": 636.35},
        {"nseCode": "LIQUIDCASE", "allocation": 0.36, "buyPrice": 112.49},
        {"nseCode": "MEESHO",     "allocation": 0.03, "buyPrice": 165.98},
        {"nseCode": "GROWW",      "allocation": 0.04, "buyPrice": 167.86},
        {"nseCode": "MOBIKWIK",   "allocation": 0.03, "buyPrice": 195.81},
        {"nseCode": "GENESYS",    "allocation": 0.04, "buyPrice": 305.48},
        {"nseCode": "URBANCO",    "allocation": 0.05, "buyPrice": 121.58},
        {"nseCode": "NPST",       "allocation": 0.04, "buyPrice": 1273.83},
        {"nseCode": "PINELABS",   "allocation": 0.04, "buyPrice": 234.92},
        {"nseCode": "MAPMYINDIA", "allocation": 0.03, "buyPrice": 1296.55},
        {"nseCode": "INTELLECT",  "allocation": 0.04, "buyPrice": 889.45},
        {"nseCode": "RSYSTEMS",   "allocation": 0.03, "buyPrice": 357.03},
        {"nseCode": "YATRA",      "allocation": 0.06, "buyPrice": 144.32},
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # MAKE IN INDIA — 20 stocks, Σ = 100%
    # ─────────────────────────────────────────────────────────────────────────
    "Make_in_India": [
        {"nseCode": "AARTIPHARM",  "allocation": 0.05, "buyPrice": 603.85},
        {"nseCode": "ASTRAMICRO",  "allocation": 0.04, "buyPrice": 1145.40},
        {"nseCode": "AVALON",      "allocation": 0.05, "buyPrice": 647.45},
        {"nseCode": "CENTUM",      "allocation": 0.05, "buyPrice": 1718.81},
        {"nseCode": "DYCL",        "allocation": 0.05, "buyPrice": 348.20},
        {"nseCode": "EIMCOELECO",  "allocation": 0.05, "buyPrice": 2278.98},
        {"nseCode": "GENESYS",     "allocation": 0.06, "buyPrice": 780.24},
        {"nseCode": "GMDCLTD",     "allocation": 0.04, "buyPrice": 605.51},
        {"nseCode": "HLEGLAS",     "allocation": 0.04, "buyPrice": 516.18},
        {"nseCode": "INDOTECH",    "allocation": 0.05, "buyPrice": 2101.58},
        {"nseCode": "KDDL",        "allocation": 0.04, "buyPrice": 1051.27},
        {"nseCode": "LIQUIDCASE",  "allocation": 0.14, "buyPrice": 111.91},
        {"nseCode": "PRECWIRE",    "allocation": 0.03, "buyPrice": 186.48},
        {"nseCode": "QUADFUTURE",  "allocation": 0.04, "buyPrice": 455.20},
        {"nseCode": "RACLGEAR",    "allocation": 0.03, "buyPrice": 970.26},
        {"nseCode": "SAMBHV",      "allocation": 0.05, "buyPrice": 101.02},
        {"nseCode": "SKIPPER",     "allocation": 0.07, "buyPrice": 241.16},
        {"nseCode": "SUPRAJIT",    "allocation": 0.04, "buyPrice": 491.76},
        {"nseCode": "VIMTALABS",   "allocation": 0.04, "buyPrice": 429.71},
        {"nseCode": "WAAREEENER",  "allocation": 0.04, "buyPrice": 2401.09},
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # CONSUMER TRENDS — 26 stocks, Σ = 100%
    # ─────────────────────────────────────────────────────────────────────────
    "Consumer_Trends": [
        {"nseCode": "GODFRYPHLP",  "allocation": 0.04, "buyPrice": 1313.79},
        {"nseCode": "SHAILY",      "allocation": 0.04, "buyPrice": 1455.76},
        {"nseCode": "MANORAMA",    "allocation": 0.04, "buyPrice": 1082.84},
        {"nseCode": "KFINTECH",    "allocation": 0.05, "buyPrice": 798.94},
        {"nseCode": "ATHERENERG",  "allocation": 0.05, "buyPrice": 698.70},
        {"nseCode": "ETERNAL",     "allocation": 0.04, "buyPrice": 233.05},
        {"nseCode": "V2RETAIL",    "allocation": 0.04, "buyPrice": 1815.59},
        {"nseCode": "ETHOSLTD",    "allocation": 0.04, "buyPrice": 2286.01},
        {"nseCode": "E2E",         "allocation": 0.04, "buyPrice": 2399.30},
        {"nseCode": "ASALCBR",     "allocation": 0.04, "buyPrice": 1183.89},
        {"nseCode": "IXIGO",       "allocation": 0.03, "buyPrice": 216.29},
        {"nseCode": "PARAGMILK",   "allocation": 0.05, "buyPrice": 264.19},
        {"nseCode": "ICEMAKE",     "allocation": 0.04, "buyPrice": 791.40},
        {"nseCode": "YATRA",       "allocation": 0.05, "buyPrice": 160.47},
        {"nseCode": "CARTRADE",    "allocation": 0.04, "buyPrice": 2862.56},
        {"nseCode": "PICCADIL",    "allocation": 0.01, "buyPrice": 686.85},
        {"nseCode": "CARYSIL",     "allocation": 0.05, "buyPrice": 951.79},
        {"nseCode": "LEMONTREE",   "allocation": 0.04, "buyPrice": 154.59},
        {"nseCode": "GOLDIAM",     "allocation": 0.05, "buyPrice": 399.75},
        {"nseCode": "INDOFARM",    "allocation": 0.02, "buyPrice": 225.52},
        {"nseCode": "GOKEX",       "allocation": 0.03, "buyPrice": 823.66},
        {"nseCode": "GRWRHITECH",  "allocation": 0.04, "buyPrice": 4097.83},
        {"nseCode": "POKARNA",     "allocation": 0.03, "buyPrice": 1050.79},
        {"nseCode": "MOLDTKPAC",   "allocation": 0.04, "buyPrice": 799.65},
        {"nseCode": "JMFINANCIL",  "allocation": 0.03, "buyPrice": 183.92},
        {"nseCode": "MOBIKWIK",    "allocation": 0.03, "buyPrice": 307.60},
    ],
}


# ── Stock History ──────────────────────────────────────────────────────────────
# Keyed by basket → NSE code.
# Each entry: { added: "DD MMM YYYY", rebalances: [{ date, note }] }
# Currently empty — portfolio manager will populate with exact dates.
STOCK_HISTORY = {
    "Green_Energy":    {},
    "Mid_Small_Cap":   {},
    "IPO_Basket":      {},
    "Trends_Triology": {},
    "Techstack":       {},
    "Make_in_India":   {},
    "Consumer_Trends": {},
}


# ── Buy Price Details ──────────────────────────────────────────────────────────
# Keyed by basket → NSE code.
# Each entry: { securityName, segment, buyEvents }
BUY_PRICE_DETAILS = {

    # ── GREEN ENERGY ──────────────────────────────────────────────────────────
    "Green_Energy": {
        "WAAREEENER":  {"securityName": "Waaree Energies Ltd",                    "segment": "Renewable/Clean Energy",           "buyEvents": "29 Oct 2024 * 5.0\n10 Dec 2024 * 2.0"},
        "TRITURBINE":  {"securityName": "Triveni Turbine Ltd",                    "segment": "Renewable/Clean Energy",           "buyEvents": "28 Apr 2021 * 10.0\n11 Aug 2022 * 1.0"},
        "TDPOWERSYS":  {"securityName": "TD Power Systems Ltd",                   "segment": "Renewable/Clean Energy",           "buyEvents": "16 Nov 2021 * 5.0\n11 Aug 2022 * 1.0\n14 Jan 2025 * 1.0"},
        "EMMVEE":      {"securityName": "Emmvee Photovoltaic Power Ltd",          "segment": "Renewable/Clean Energy",           "buyEvents": "19 Nov 2025 * 3.0"},
        "BORORENEW":   {"securityName": "Borosil Renewables Ltd",                 "segment": "Renewable/Clean Energy",           "buyEvents": "10 Dec 2024 * 4.0\n14 Jan 2025 * 2.0"},
        "VEDL":        {"securityName": "Vedanta Ltd",                            "segment": "Metals - Diversified",             "buyEvents": "16 Mar 2026 * 4.0"},
        "TRANSRAILL":  {"securityName": "Transrail Lighting Ltd",                 "segment": "Power Infrastructure",             "buyEvents": "14 Jan 2025 * 2.5\n30 Jan 2025 * 1.0"},
        "TATAPOWER":   {"securityName": "Tata Power Company Ltd",                 "segment": "Power Infrastructure",             "buyEvents": "23 Jul 2025 * 4.0"},
        "SKIPPER":     {"securityName": "Skipper Ltd",                            "segment": "Power Infrastructure",             "buyEvents": "01 Sep 2023 * 4.0\n01 Feb 2024 * 1.0"},
        "POWERMECH":   {"securityName": "Power Mech Projects Ltd",                "segment": "Power Infrastructure",             "buyEvents": "23 May 2025 * 3.0"},
        "ENRIN":       {"securityName": "Siemens Energy India Ltd",               "segment": "Power Infrastructure",             "buyEvents": "03 Feb 2026 * 3.0\n16 Mar 2026 * 2.0"},
        "THERMAX":     {"securityName": "Thermax Limited",                        "segment": "Industrial Machinery",             "buyEvents": "16 Mar 2026 * 3.0"},
        "SYRMA":       {"securityName": "Syrma SGS Technology Ltd",               "segment": "Electronics",                      "buyEvents": "27 Feb 2025 * 4.0\n03 Feb 2026 * 2.0"},
        "AVALON":      {"securityName": "Avalon Technologies Ltd",                "segment": "Electronics",                      "buyEvents": "03 Feb 2026 * 3.0"},
        "SBCL":        {"securityName": "Shivalik Bimetal Controls Ltd",          "segment": "Electrical Mobility",              "buyEvents": "17 Aug 2021 * 5.0\n18 Apr 2022 * 1.0\n11 Aug 2022 * 2.0\n17 Oct 2022 * 2.0"},
        "FIEMIND":     {"securityName": "Fiem Industries Ltd",                    "segment": "Electrical Mobility",              "buyEvents": "17 Oct 2022 * 5.0"},
        "ATHERENERG":  {"securityName": "Ather Energy Ltd",                       "segment": "Electrical Mobility",              "buyEvents": "19 Nov 2025 * 3.0"},
        "SANSERA":     {"securityName": "Sansera Engineering Ltd",                "segment": "Capital Goods",                    "buyEvents": "03 Feb 2026 * 3.0\n16 Mar 2026 * 1.5"},
        "JASH":        {"securityName": "Jash Engineering Ltd",                   "segment": "Capital Goods",                    "buyEvents": "14 Jan 2025 * 2.0\n27 Feb 2025 * 2.0"},
        "QPOWER":      {"securityName": "Quality Power Electrical Equipments Ltd","segment": "Power Trading & Consultancy",      "buyEvents": "16 Mar 2026 * 2.0"},
        "POCL":        {"securityName": "Pondy Oxides and Chemicals Ltd",         "segment": "Recycling",                        "buyEvents": "04 Sep 2024 * 3.0\n29 Oct 2024 * 1.0\n10 Nov 2025 * 0.5"},
        "JAINREC":     {"securityName": "Jain Resource Recycling Ltd",            "segment": "Recycling",                        "buyEvents": "10 Nov 2025 * 3.5"},
        "GANECOS":     {"securityName": "Ganesha Ecosphere Ltd",                  "segment": "Recycling",                        "buyEvents": "18 Apr 2022 * 5.0\n17 Oct 2022 * 1.0"},
        "EBGNG":       {"securityName": "GNG Electronics Ltd",                    "segment": "Recycling",                        "buyEvents": "31 Jul 2025 * 4.0\n10 Nov 2025 * 1.0"},
        "NEOGEN":      {"securityName": "Neogen Chemicals Ltd",                   "segment": "Chemical",                         "buyEvents": "03 Feb 2026 * 2.0"},
        "LIQUIDCASE":  {"securityName": "Zerodha Nifty 1D Rate Liquid ETF",       "segment": "Cash",                             "buyEvents": "10 Nov 2025 * 3.0\n03 Feb 2026 * 6.0"},
        "HBLENGINE":   {"securityName": "HBL Engineering Ltd",                    "segment": "Industrials",                      "buyEvents": "30 Jan 2025 * 5.0\n10 Nov 2025 * 1.0"},
    },

    # ── MID & SMALL CAP ───────────────────────────────────────────────────────
    "Mid_Small_Cap": {
        "AARTIPHARM":  {"securityName": "Aarti Pharmalabs Ltd",                        "segment": "Pharmaceuticals",        "buyEvents": "18 Feb 2025 * 3.0\n09 Jan 2026 * 1.0"},
        "ACUTAAS":     {"securityName": "Acutaas Chemicals Ltd",                       "segment": "Pharmaceuticals",        "buyEvents": "18 Feb 2025 * 3.0\n09 Jan 2026 * 1.0"},
        "ASTRAMICRO":  {"securityName": "Astra Microwave Products Ltd",                "segment": "Defence",                "buyEvents": "23 May 2025 * 3.0\n19 Aug 2025 * 1.0"},
        "BORORENEW":   {"securityName": "Borosil Renewables Ltd",                      "segment": "Renewables",             "buyEvents": "18 Feb 2025 * 3.0\n30 Jul 2025 * 2.0"},
        "CENTUM":      {"securityName": "Centum Electronics Ltd",                      "segment": "Electronics",            "buyEvents": "06 Aug 2025 * 3.0\n19 Aug 2025 * 1.0\n20 Feb 2026 * 1.0"},
        "GANECOS":     {"securityName": "Ganesha Ecosphere Ltd",                       "segment": "Recycling",              "buyEvents": "04 Nov 2022 * 5.0\n21 Dec 2022 * 2.0\n28 May 2024 * 1.01"},
        "GENESYS":     {"securityName": "Genesys International Corporation Ltd",       "segment": "IT Software",            "buyEvents": "23 Oct 2024 * 4.0\n29 Oct 2024 * 1.0"},
        "GOKEX":       {"securityName": "Gokaldas Exports Ltd",                        "segment": "Apparel & Accessories",  "buyEvents": "20 Feb 2026 * 3.0"},
        "GOLDIAM":     {"securityName": "Goldiam International Ltd",                   "segment": "Consumption",            "buyEvents": "19 Nov 2025 * 2.5\n11 Feb 2026 * 1.0"},
        "GROWW":       {"securityName": "Billionbrains Garage Ventures Ltd",           "segment": "Financial Services",     "buyEvents": "11 Feb 2026 * 4.0"},
        "HBLENGINE":   {"securityName": "HBL Engineering Ltd",                         "segment": "Power",                  "buyEvents": "21 Jun 2023 * 4.0\n16 Aug 2023 * 1.0\n18 Feb 2025 * 1.0\n23 May 2025 * 1.0"},
        "HLEGLAS":     {"securityName": "HLE Glascoat Ltd",                            "segment": "Capital Goods",          "buyEvents": "19 Aug 2025 * 2.5"},
        "IMFA":        {"securityName": "Indian Metals and Ferro Alloys Ltd",          "segment": "Metals & Minings",       "buyEvents": "19 Nov 2025 * 3.0\n09 Jan 2026 * 1.0"},
        "INTELLECT":   {"securityName": "Intellect Design Arena Ltd",                  "segment": "IT Software",            "buyEvents": "19 Nov 2025 * 3.0"},
        "INTERARCH":   {"securityName": "Interarch Building Solutions Ltd",            "segment": "Infrastructure",         "buyEvents": "23 Oct 2024 * 3.0\n23 May 2025 * 1.0"},
        "KDDL":        {"securityName": "KDDL Ltd",                                    "segment": "Consumption",            "buyEvents": "21 Dec 2022 * 5.0\n07 Feb 2023 * 1.0"},
        "KRN":         {"securityName": "KRN Heat Exchanger and Refrigeration Ltd",    "segment": "Capital Goods",          "buyEvents": "19 Nov 2025 * 3.0"},
        "LIQUIDCASE":  {"securityName": "Zerodha Nifty 1D Rate Liquid ETF",            "segment": "Debt",                   "buyEvents": "20 Feb 2026 * 5.5"},
        "MOLDTKPAC":   {"securityName": "Mold-Tek Packaging Ltd",                      "segment": "Capital Goods",          "buyEvents": "30 Jul 2025 * 3.0"},
        "SAMBHV":      {"securityName": "Sambhv Steel Tubes Ltd",                      "segment": "Capital Goods",          "buyEvents": "03 Jul 2025 * 4.0\n20 Feb 2026 * 1.0"},
        "SANSERA":     {"securityName": "Sansera Engineering Ltd",                     "segment": "Auto Ancillary",         "buyEvents": "11 Feb 2026 * 5.0"},
        "SBCL":        {"securityName": "Shivalik Bimetal Controls Ltd",               "segment": "Auto Ancillary",         "buyEvents": "04 Aug 2021 * 3.0\n19 Apr 2022 * 2.0\n11 May 2022 * 2.0\n11 Aug 2022 * 1.0\n11 Feb 2026 * 1.0"},
        "SJS":         {"securityName": "SJS Enterprises Ltd",                         "segment": "Auto Ancillary",         "buyEvents": "19 Nov 2025 * 2.5"},
        "SUPRAJIT":    {"securityName": "Suprajit Engineering Ltd",                    "segment": "Auto Ancillary",         "buyEvents": "09 Jan 2026 * 3.0"},
        "SYRMA":       {"securityName": "Syrma SGS Technology Ltd",                    "segment": "Capital Goods",          "buyEvents": "02 Jun 2025 * 3.0"},
        "TDPOWERSYS":  {"securityName": "TD Power Systems Ltd",                        "segment": "Capital Goods",          "buyEvents": "04 Mar 2025 * 2.5"},
        "URBANCO":     {"securityName": "Urban Company Ltd",                           "segment": "Consumption",            "buyEvents": "09 Jan 2026 * 2.5"},
        "WAAREEENER":  {"securityName": "Waaree Energies Ltd",                         "segment": "Renewables",             "buyEvents": "29 Oct 2024 * 5.0"},
        "ZENTEC":      {"securityName": "Zen Technologies Ltd",                        "segment": "Defence",                "buyEvents": "07 Jun 2024 * 3.0"},
    },

    # ── IPO BASKET ────────────────────────────────────────────────────────────
    "IPO_Basket": {
        "AJAXENGG":    {"securityName": "AJAX Engineering Ltd",                         "segment": "Capital Goods",             "buyEvents": "25 Mar 2025 * 4.0"},
        "ALLTIME":     {"securityName": "All Time Plastics Ltd",                        "segment": "Consumption",               "buyEvents": "28 Aug 2025 * 3.0"},
        "ARIS":        {"securityName": "Arisinfra Solutions Ltd",                      "segment": "Infrastructure",            "buyEvents": "27 Jun 2025 * 4.0"},
        "ATHERENERG":  {"securityName": "Ather Energy Ltd",                             "segment": "Consumption",               "buyEvents": "28 Aug 2025 * 2.5\n21 Nov 2025 * 1.5\n16 Dec 2025 * 1.0"},
        "BLACKBUCK":   {"securityName": "Blackbuck Ltd",                                "segment": "Miscellaneous",             "buyEvents": "17 Feb 2025 * 2.5\n25 Mar 2025 * 1.5\n05 Feb 2026 * 1.0"},
        "CPPLUS":      {"securityName": "Aditya Infotech Ltd",                          "segment": "Miscellaneous",             "buyEvents": "21 Nov 2025 * 2.5\n05 Feb 2026 * 1.0"},
        "EBGNG":       {"securityName": "GNG Electronics Ltd",                          "segment": "Recycling",                 "buyEvents": "31 Jul 2025 * 4.0\n16 Dec 2025 * 1.0\n18 Feb 2026 * 2.0"},
        "EMMVEE":      {"securityName": "Emmvee Photovoltaic Power Ltd",                "segment": "Power & Renewable Energy",  "buyEvents": "21 Nov 2025 * 3.0"},
        "EPACKPEB":    {"securityName": "EPack Prefab Technologies Ltd",                "segment": "Infrastructure",            "buyEvents": "16 Dec 2025 * 4.0"},
        "GROWW":       {"securityName": "Billionbrains Garage Ventures Ltd",            "segment": "Financial Services",        "buyEvents": "05 Feb 2026 * 4.0"},
        "INTERARCH":   {"securityName": "Interarch Building Solutions Ltd",             "segment": "Infrastructure",            "buyEvents": "17 Feb 2025 * 4.0"},
        "IXIGO":       {"securityName": "Le Travenues Technology Ltd",                  "segment": "Consumption",               "buyEvents": "21 Jul 2025 * 3.0"},
        "JAINREC":     {"securityName": "Jain Resource Recycling Ltd",                  "segment": "Recycling",                 "buyEvents": "21 Nov 2025 * 2.5\n16 Dec 2025 * 2.5"},
        "KRN":         {"securityName": "KRN Heat Exchanger and Refrigeration Ltd",     "segment": "Miscellaneous",             "buyEvents": "17 Feb 2025 * 3.0\n25 Mar 2025 * 1.0"},
        "LAXMIDENTL":  {"securityName": "Laxmi Dental Ltd",                             "segment": "Miscellaneous",             "buyEvents": "21 Nov 2025 * 2.5\n16 Dec 2025 * 1.0"},
        "MEESHO":      {"securityName": "Meesho Ltd",                                   "segment": "E-commerce",                "buyEvents": "05 Feb 2026 * 3.0"},
        "MOBIKWIK":    {"securityName": "One MobiKwik Systems Ltd",                     "segment": "Financial Services",        "buyEvents": "05 Feb 2026 * 4.0"},
        "QPOWER":      {"securityName": "Quality Power Electrical Equipments Ltd",      "segment": "Capital Goods",             "buyEvents": "18 Feb 2026 * 5.0"},
        "SAILIFE":     {"securityName": "Sai Life Sciences Ltd",                        "segment": "Pharma/Chemicals",          "buyEvents": "17 Feb 2025 * 4.0"},
        "SAMBHV":      {"securityName": "Sambhv Steel Tubes Ltd",                       "segment": "Capital Goods",             "buyEvents": "03 Jul 2025 * 7.0"},
        "SETL":        {"securityName": "Standard Engineering Technology Ltd",          "segment": "Capital Goods",             "buyEvents": "27 Jun 2025 * 4.0"},
        "UNIMECH":     {"securityName": "Unimech Aerospace and Manufacturing Ltd",      "segment": "Capital Goods",             "buyEvents": "30 Apr 2025 * 3.0"},
        "URBANCO":     {"securityName": "Urban Company Ltd",                            "segment": "Retail",                    "buyEvents": "05 Feb 2026 * 4.0"},
        "WAAREEENER":  {"securityName": "Waaree Energies Ltd",                          "segment": "Power & Renewable Energy",  "buyEvents": "17 Feb 2025 * 4.0"},
    },

    # ── TRENDS TRIOLOGY ───────────────────────────────────────────────────────
    "Trends_Triology": {
        "AARTIPHARM":  {"securityName": None, "segment": None, "buyEvents": "06 Feb 2025 * 5.0"},
        "ACUTAAS":     {"securityName": None, "segment": None, "buyEvents": "30 Dec 2025 * 7.0"},
        "AEROFLEX":    {"securityName": None, "segment": None, "buyEvents": None},
        "AETHER":      {"securityName": None, "segment": None, "buyEvents": "16 Feb 2026 * 5.0"},
        "ATHERENERG":  {"securityName": None, "segment": None, "buyEvents": "12 Feb 2026 * 5.0"},
        "CENTUM":      {"securityName": None, "segment": None, "buyEvents": "20 Feb 2026 * 5.0"},
        "DYNAMATECH":  {"securityName": None, "segment": None, "buyEvents": "30 Dec 2025 * 7.0"},
        "E2E":         {"securityName": None, "segment": None, "buyEvents": "05 Sep 2024 * 8.0"},
        "EBGNG":       {"securityName": None, "segment": None, "buyEvents": "20 Feb 2026 * 5.0\n16 Mar 2026 * 1.0"},
        "GENESYS":     {"securityName": None, "segment": None, "buyEvents": "22 Nov 2024 * 8.0"},
        "GROWW":       {"securityName": None, "segment": None, "buyEvents": "12 Feb 2026 * 5.0"},
        "ICEMAKE":     {"securityName": None, "segment": None, "buyEvents": "16 Feb 2026 * 3.0"},
        "NEOGEN":      {"securityName": None, "segment": None, "buyEvents": "16 Feb 2026 * 3.0"},
        "RACLGEAR":    {"securityName": None, "segment": None, "buyEvents": "16 Feb 2026 * 3.0"},
        "SAILIFE":     {"securityName": None, "segment": None, "buyEvents": None},
        "SAMBHV":      {"securityName": None, "segment": None, "buyEvents": "20 Feb 2026 * 5.0"},
        "SANSERA":     {"securityName": None, "segment": None, "buyEvents": "16 Mar 2026 * 5.0"},
        "SHAILY":      {"securityName": None, "segment": None, "buyEvents": "12 Aug 2025 * 8.0"},
        "WAAREEENER":  {"securityName": None, "segment": None, "buyEvents": "30 Jul 2025 * 5.0"},
    },

    # ── TECHSTACK ─────────────────────────────────────────────────────────────
    "Techstack": {
        "ATHERENERG":  {"securityName": None, "segment": "Electronics, Hardware & Deep-Tech Manufacturing",  "buyEvents": None},
        "BLACKBUCK":   {"securityName": None, "segment": "Electronics, Hardware & Deep-Tech Manufacturing",  "buyEvents": None},
        "E2E":         {"securityName": None, "segment": "Digital Infrastructure & Connectivity",            "buyEvents": None},
        "GENESYS":     {"securityName": None, "segment": "Digital Infrastructure & Connectivity",            "buyEvents": None},
        "GROWW":       {"securityName": None, "segment": "Fintech & Digital Public Rail",                    "buyEvents": None},
        "INTELLECT":   {"securityName": None, "segment": "Software, Data & Cyber",                           "buyEvents": None},
        "LENSKART":    {"securityName": None, "segment": "Platforms & Digital Consumption",                  "buyEvents": None},
        "LIQUIDCASE":  {"securityName": "Zerodha Nifty 1D Rate Liquid ETF", "segment": "Cash",               "buyEvents": None},
        "MAPMYINDIA":  {"securityName": None, "segment": "Digital Infrastructure & Connectivity",            "buyEvents": None},
        "MEESHO":      {"securityName": None, "segment": "Platforms & Digital Consumption",                  "buyEvents": None},
        "MOBIKWIK":    {"securityName": None, "segment": "Fintech & Digital Public Rail",                    "buyEvents": None},
        "NPST":        {"securityName": None, "segment": "Fintech & Digital Public Rail",                    "buyEvents": None},
        "PARAS":       {"securityName": None, "segment": "Electronics, Hardware & Deep-Tech Manufacturing",  "buyEvents": None},
        "PINELABS":    {"securityName": None, "segment": "Fintech & Digital Public Rail",                    "buyEvents": None},
        "RSYSTEMS":    {"securityName": None, "segment": "Software, Data & Cyber",                           "buyEvents": None},
        "URBANCO":     {"securityName": None, "segment": "Platforms & Digital Consumption",                  "buyEvents": None},
        "YATRA":       {"securityName": None, "segment": "Platforms & Digital Consumption",                  "buyEvents": None},
    },

    # ── MAKE IN INDIA ─────────────────────────────────────────────────────────
    "Make_in_India": {
        "AARTIPHARM":  {"securityName": "Aarti Pharmalabs Ltd",                        "segment": "Labs & Life Sciences Services", "buyEvents": "12 Jun 2024 * 4.0\n31 Jan 2025 * 2.0"},
        "ASTRAMICRO":  {"securityName": "Astra Microwave Products Ltd",                "segment": "Defence",                       "buyEvents": "03 Jun 2025 * 4.0"},
        "AVALON":      {"securityName": "Avalon Technologies Ltd",                     "segment": "Electronics",                   "buyEvents": "31 Jan 2025 * 5.0"},
        "CENTUM":      {"securityName": "Centum Electronics Ltd",                      "segment": "Electronics",                   "buyEvents": "24 Jul 2023 * 5.0\n03 Jun 2025 * 2.0"},
        "DYCL":        {"securityName": "Dynamic Cables Ltd",                          "segment": "Cables",                        "buyEvents": "12 Jun 2024 * 3.03\n29 Oct 2024 * 2.0"},
        "EIMCOELECO":  {"securityName": "Eimco Elecon (India) Ltd",                    "segment": "Industrial Machinery",          "buyEvents": "12 Jun 2024 * 3.03\n29 Oct 2024 * 2.0"},
        "GENESYS":     {"securityName": "Genesys International Corporation Ltd",       "segment": "IT Services & Consulting",      "buyEvents": "29 Oct 2024 * 4.0\n31 Jan 2025 * 2.0"},
        "GMDCLTD":     {"securityName": "Gujarat Mineral Development Corporation Ltd", "segment": "Minerals & Mining",             "buyEvents": "25 Sep 2025 * 4.0"},
        "HLEGLAS":     {"securityName": "HLE Glascoat Ltd",                            "segment": "Capital Goods",                 "buyEvents": "25 Sep 2025 * 4.0"},
        "INDOTECH":    {"securityName": "Indo Tech Transformers Ltd",                  "segment": "Heavy Electrical Equipments",   "buyEvents": "29 Oct 2024 * 5.0"},
        "KDDL":        {"securityName": "KDDL Ltd",                                    "segment": "Consumption",                   "buyEvents": "15 Dec 2022 * 6.0\n16 Feb 2023 * 1.0"},
        "LIQUIDCASE":  {"securityName": "Zerodha Nifty 1D Rate Liquid ETF",            "segment": "Cash",                          "buyEvents": "10 Nov 2025 * 5.0\n09 Jan 2026 * 9.0"},
        "PRECWIRE":    {"securityName": "Precision Wires India Ltd",                   "segment": "Capital Goods",                 "buyEvents": "03 Jun 2025 * 3.0"},
        "QUADFUTURE":  {"securityName": "Quadrant Future Tek Ltd",                     "segment": "Capital Goods",                 "buyEvents": "03 Jun 2025 * 4.0"},
        "RACLGEAR":    {"securityName": "RACL Geartech Ltd",                           "segment": "Auto Components",               "buyEvents": "25 Sep 2025 * 3.0"},
        "SAMBHV":      {"securityName": "Sambhv Steel Tubes Ltd",                      "segment": "Capital Goods",                 "buyEvents": "03 Jul 2025 * 5.0"},
        "SKIPPER":     {"securityName": "Skipper Ltd",                                 "segment": "Infrastructure",                "buyEvents": "24 Jul 2023 * 5.0\n31 Jan 2025 * 2.0"},
        "SUPRAJIT":    {"securityName": "Suprajit Engineering Ltd",                    "segment": "Auto Components",               "buyEvents": "25 Sep 2025 * 4.0"},
        "VIMTALABS":   {"securityName": "Vimta Labs Ltd",                              "segment": "Health Care",                   "buyEvents": "31 Jan 2025 * 5.0"},
        "WAAREEENER":  {"securityName": "Waaree Energies Ltd",                         "segment": "Capital Goods",                 "buyEvents": "29 Oct 2024 * 4.0"},
    },

    # ── CONSUMER TRENDS ───────────────────────────────────────────────────────
    "Consumer_Trends": {
        "ASALCBR":     {"securityName": "Associated Alcohols & Breweries Ltd", "segment": "Consumer Staples",                     "buyEvents": "20 Feb 2025 * 4.0"},
        "ATHERENERG":  {"securityName": "Ather Energy Ltd",                    "segment": "Electric Mobility",                    "buyEvents": "21 Nov 2025 * 4.0\n05 Feb 2026 * 1.0"},
        "CARYSIL":     {"securityName": "Carysil Ltd",                         "segment": "Building Products & Materials",        "buyEvents": "03 May 2024 * 5.05"},
        "CARTRADE":    {"securityName": "Cartrade Tech Ltd",                   "segment": "Auto Ancilliary",                      "buyEvents": "21 Nov 2025 * 3.0\n05 Feb 2026 * 1.0"},
        "E2E":         {"securityName": "E2E Networks Ltd",                    "segment": "Information Technology",               "buyEvents": "28 Aug 2025 * 4.0"},
        "ETERNAL":     {"securityName": "Eternal Ltd",                         "segment": "Communication Services",               "buyEvents": "20 Feb 2025 * 4.0"},
        "ETHOSLTD":    {"securityName": "Ethos Ltd",                           "segment": "Consumer Discretionary",               "buyEvents": "03 May 2024 * 5.05"},
        "GODFRYPHLP":  {"securityName": "Godfrey Phillips India Ltd",          "segment": "FMCG",                                 "buyEvents": "03 May 2024 * 4.04\n20 Feb 2025 * 1.0"},
        "GOKEX":       {"securityName": "Gokaldas Exports Ltd",                "segment": "Textile",                              "buyEvents": "05 Feb 2026 * 3.0"},
        "GOLDIAM":     {"securityName": "Goldiam International Ltd",           "segment": "Consumer Discretionary",               "buyEvents": "20 Feb 2025 * 5.0"},
        "GRWRHITECH":  {"securityName": "Garware Hi-Tech Films Ltd",           "segment": "Auto Ancilliary",                      "buyEvents": "21 Nov 2025 * 4.0"},
        "ICEMAKE":     {"securityName": "Ice Make Refrigeration Ltd",          "segment": "Electrical Components & Equipments",   "buyEvents": "12 Jun 2024 * 4.0"},
        "INDOFARM":    {"securityName": "Indo Farm Equipment Ltd",             "segment": "Industrials",                          "buyEvents": "28 Aug 2025 * 4.0"},
        "IXIGO":       {"securityName": "Le Travenues Technology Ltd",         "segment": "Travel",                               "buyEvents": "21 Jul 2025 * 3.0"},
        "JMFINANCIL":  {"securityName": "JM Financial Ltd",                    "segment": "Financials",                           "buyEvents": "28 Aug 2025 * 3.0"},
        "KFINTECH":    {"securityName": "Kfin Technologies Ltd",               "segment": "Financials",                           "buyEvents": "03 May 2024 * 5.05"},
        "LEMONTREE":   {"securityName": "Lemon Tree Hotels Ltd",               "segment": "Travel",                               "buyEvents": "03 May 2024 * 4.04"},
        "MANORAMA":    {"securityName": "Manorama Industries Ltd",             "segment": "Consumer Staples",                     "buyEvents": "20 Feb 2025 * 4.0"},
        "MOBIKWIK":    {"securityName": "One MobiKwik Systems Ltd",            "segment": "Financials",                           "buyEvents": "11 Sep 2025 * 3.0"},
        "MOLDTKPAC":   {"securityName": "Mold-Tek Packaging Ltd",              "segment": "Industrials",                          "buyEvents": "28 Aug 2025 * 4.0"},
        "PARAGMILK":   {"securityName": "Parag Milk Foods Ltd",                "segment": "FMCG",                                 "buyEvents": "11 Sep 2025 * 4.0\n05 Feb 2026 * 1.0"},
        "PICCADIL":    {"securityName": "Piccadily Agro Industries Ltd",       "segment": "FMCG",                                 "buyEvents": "11 Sep 2025 * 4.0"},
        "POKARNA":     {"securityName": "Pokarna Ltd",                         "segment": "Consumer Durables",                    "buyEvents": "05 Feb 2026 * 3.0"},
        "SHAILY":      {"securityName": "Shaily Engineering Plastics Ltd",     "segment": "Industrials",                          "buyEvents": "20 Feb 2025 * 4.0"},
        "V2RETAIL":    {"securityName": "V2 Retail Ltd",                       "segment": "Textile",                              "buyEvents": "04 Apr 2025 * 5.0"},
        "YATRA":       {"securityName": "Yatra Online Ltd",                    "segment": "Travel",                               "buyEvents": "28 Aug 2025 * 3.0\n21 Nov 2025 * 2.0"},
    },
}
